databases:
  - name: snake-arena-db
    databaseName: snake_arena
    user: snake_user
    plan: free

services:
  - type: web
    name: snake-arena-app
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snake-arena-db
          property: connectionString
      - key: PORT
        value: 8081
